services:
  frontend:
    build:
      context: ./viment
      dockerfile: Dockerfile
    volumes:
      - ./viment:/app
      - /app/node_modules #Evita que el contenedor utilice el node modules de la maquina windows
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - app-network
  backend:
    build:
      context: ./coduct
      dockerfile: Dockerfile
    volumes:
       - ./coduct:/app
       - /app/node_modules #Evita que el contenedor utilice el node modules de la maquina windows
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - app-network
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge